/* Drop Tables */

DROP TABLE FREEBOARD CASCADE CONSTRAINTS;
DROP TABLE REVIEWBOARD CASCADE CONSTRAINTS;
DROP TABLE TIPBOARD CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE "FILE" CASCADE CONSTRAINTS;
DROP TABLE BOARDID CASCADE CONSTRAINTS;
DROP TABLE WRITEID CASCADE CONSTRAINTS;

/* Drop Sequences */

DROP SEQUENCE ACCOUNT_SEQ;
DROP SEQUENCE BOARD_ID_SEQ;
DROP SEQUENCE WRITE_ID_SEQ;
DROP SEQUENCE FILE_ID_SEQ;

/* Ceate Sequence */

CREATE SEQUENCE ACCOUNT_SEQ;
CREATE SEQUENCE BOARD_ID_SEQ;
CREATE SEQUENCE WRITE_ID_SEQ;
CREATE SEQUENCE FILE_ID_SEQ;

/* Create Tables */

CREATE TABLE ACCOUNT
(
	ACCNUM number NOT NULL,
	ID varchar2(20) NOT NULL UNIQUE,
	PW varchar2(30) NOT NULL,
	NAME varchar2(30) NOT NULL,
	EMAIL varchar2(30) NOT NULL,
	BIRTH date NOT NULL,
	GENDER varchar2(20) NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	NICKNAME varchar2(20) NOT NULL UNIQUE,
	PRIMARY KEY (ACCNUM)
);


CREATE TABLE BOARDID
(
	BOARD_ID number NOT NULL,
	BOARD_NAME varchar2(20) NOT NULL UNIQUE,
	PRIMARY KEY (BOARD_ID)
);


CREATE TABLE "FILE"
(
	FILE_ID number NOT NULL,
	SYSTEMNAME varchar2(50) NOT NULL UNIQUE,
	ORIGINALNAME varchar2(50) NOT NULL,
	FILESEQ number NOT NULL,
	BOARD_ID number NOT NULL,
	WRITE_ID number NOT NULL,
	PRIMARY KEY (FILE_ID)
);


CREATE TABLE FREEBOARD
(
	ACCNUM number NOT NULL,
	BOARD_ID number NOT NULL,
	WRITE_ID number NOT NULL,
	PRIMARY KEY (WRITE_ID)
);


CREATE TABLE REVIEWBOARD
(
	ACCNUM number NOT NULL,
	BOARD_ID number NOT NULL,
	WRITE_ID number NOT NULL,
	RATING number NOT NULL,
	PRIMARY KEY (WRITE_ID)
);


CREATE TABLE TIPBOARD
(
	ACCNUM number NOT NULL,
	BOARD_ID number NOT NULL,
	WRITE_ID number NOT NULL,
	PRIMARY KEY (WRITE_ID)
);


CREATE TABLE WRITEID
(
	WRITE_ID number NOT NULL,
	SUBJECT varchar2(50) NOT NULL,
	CONTENT clob NOT NULL,
	REGDATE date DEFAULT SYSDATE NOT NULL,
	VIEWCNT NUMBER DEFAULT 0 NOT NULL,
	PRIMARY KEY (WRITE_ID)
);

/* Create Foreign Keys */

ALTER TABLE FREEBOARD
	ADD FOREIGN KEY (ACCNUM)
	REFERENCES ACCOUNT (ACCNUM)
;


ALTER TABLE REVIEWBOARD
	ADD FOREIGN KEY (ACCNUM)
	REFERENCES ACCOUNT (ACCNUM)
;


ALTER TABLE TIPBOARD
	ADD FOREIGN KEY (ACCNUM)
	REFERENCES ACCOUNT (ACCNUM)
;


ALTER TABLE "FILE"
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES BOARDID (BOARD_ID)
;


ALTER TABLE FREEBOARD
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES BOARDID (BOARD_ID)
;


ALTER TABLE REVIEWBOARD
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES BOARDID (BOARD_ID)
;


ALTER TABLE TIPBOARD
	ADD FOREIGN KEY (BOARD_ID)
	REFERENCES BOARDID (BOARD_ID)
;


ALTER TABLE "FILE"
	ADD FOREIGN KEY (WRITE_ID)
	REFERENCES WRITEID (WRITE_ID)
;


ALTER TABLE FREEBOARD
	ADD FOREIGN KEY (WRITE_ID)
	REFERENCES WRITEID (WRITE_ID)
;


ALTER TABLE REVIEWBOARD
	ADD FOREIGN KEY (WRITE_ID)
	REFERENCES WRITEID (WRITE_ID)
;


ALTER TABLE TIPBOARD
	ADD FOREIGN KEY (WRITE_ID)
	REFERENCES WRITEID (WRITE_ID)
;

SELECT * FROM ACCOUNT;

INSERT INTO BOARDID VALUES (1, '자유게시판');
INSERT INTO BOARDID VALUES (2, '팁게시판');
INSERT INTO BOARDID VALUES (3, '평가게시판');

SELECT * FROM BOARDID;

SELECT * FROM FREEBOARD;

SELECT * FROM WRITEID;

SELECT * FROM WRITEID, FREEBOARD;

INSERT INTO WRITEID (WRITE_ID, SUBJECT, CONTENT, VIEWCNT)
VALUES (WRITE_ID_SEQ.nextval, 'FF', 'FF', 1);

INSERT INTO FREEBOARD VALUES (8, 1, 8);

SELECT A.ID, A.NICKNAME, W.SUBJECT, W.CONTENT, W.REGDATE, W.VIEWCNT, W.WRITE_ID, F.ACCNUM, F.BOARD_ID
FROM WRITEID W, FREEBOARD F, ACCOUNT A
WHERE W.WRITE_ID = F.WRITE_ID AND A.ACCNUM = F.ACCNUM;

SELECT A.ID, A.NICKNAME, W.SUBJECT, W.CONTENT, W.REGDATE, W.VIEWCNT, W.WRITE_ID, F.ACCNUM, F.BOARD_ID 
FROM WRITEID W, FREEBOARD F, ACCOUNT A 
WHERE W.WRITE_ID = F.WRITE_ID AND A.ACCNUM = F.ACCNUM AND W.WRITE_ID = 4;

SELECT A.ID, A.NICKNAME, W.SUBJECT, W.CONTENT, W.REGDATE, W.VIEWCNT, W.WRITE_ID, F.ACCNUM, F.BOARD_ID 
FROM WRITEID W
INNER JOIN FREEBOARD F
ON W.WRITE_ID = F.WRITE_ID
INNER JOIN ACCOUNT A 
ON A.ACCNUM = F.ACCNUM;

SELECT WRITE_ID_SEQ + 1 FROM DUAL;

SELECT WRITE_ID_SEQ.CURRVAL FROM DUAL;

SELECT * FROM "FILE" F
INNER JOIN BOARDID B
ON F.BOARD_ID = B.BOARD_ID
INNER JOIN WRITEID W
ON F.WRITE_ID = W.WRITE_ID;

